### ISSUE TITLE
NoClassDefFoundError : Version: 1.5-snapshot 

### ISSUE THREAD

**Issue by saikatmohajan** [DigitalPebble/storm-crawler#458]
**java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.common.network.NetworkService
	at org.elasticsearch.client.transport.TransportClient.newPluginService(TransportClient.java:98) ~[stormjar.jar:?]**
	
I am getting this error when using storm crawler version 1.5- snapshot which uses elasticsearch 5.3.0. I ran the following command to inject the seed file to elasticsearch and getting the error:
**storm jar myjar-2.0-SNAPSHOT.jar com.digitalpebble.stormcrawler.elasticsearch.ESSeedInjector / seeds.txt -conf es-conf.yaml**

My code was working with storm crawler 1.4, but I needed to use elastic search 5.3.0. So, I am trying to build my code with 1.5-snapshot. myjar-2.0-SNAPSHOT.jar contains all the dependencies including org.elasticsearch dependencies. But, for some reason storm isn't picking up the elasticsearch library.  

Thanks
Saikat

**Comment by jnioche** [comment]
Hi, did you upgrade the log4j and slf4j dependencies (see STORM-2326) in your Storm installation? This won't be necessary in the next release of Apache Storm.

**Comment by saikatmohajan** [comment]
Thank you @jnioche for your quick response. I upgraded the log4j libraries in my storm installation. But , still having the issue. I upagraded log4j-api, log4j-core, log4j-slf4j-impl from 2.1 to 2.8 and sl4j-api from 1.7.7 to 1.7.21 in my storm installation i.e. in /usr/hdp/2.5.0.0-1245/storm/lib folder in all nodes in the cluster. also restarted the cluster, but the issues remains to be the same. Is there anything else that I am missing. Thank you again for your help.

**Comment by jnioche** [comment]
Do you have a longer stack trace?

**Comment by jnioche** [comment]
Also  with ES5 we have to specify

```
	<manifestEntries>
									    <Change></Change>
									    <Build-Date></Build-Date>
									</manifestEntries>
```
for maven shade. See 
https://github.com/DigitalPebble/stormcrawlerfight/blob/es5.3/pom.xml#L66

**Comment by saikatmohajan** [comment]
Looks like the issue is related to manifest. However, I have the manifestEntries in my pom. here is my pom and the detail stack trace. and also I see that the latest jars are being picked up.
**pom.xml**
<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <storm.core.version>1.0.2</storm.core.version>
    <storm.crawler.version>1.5-SNAPSHOT</storm.crawler.version>
    <flux.core.version>1.0.2</flux.core.version>
    <phantomjs.driver.version>1.3.0</phantomjs.driver.version>
    <xsoup.version>0.3.1</xsoup.version>
    <crawler-commons.version>0.7</crawler-commons.version>
    <elasticsearch.version>5.3.0</elasticsearch.version>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.2</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>1.3.2</version>
				<executions>
					<execution>
						<goals>
							<goal>exec</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<executable>java</executable>
					<includeProjectDependencies>true</includeProjectDependencies>
					<includePluginDependencies>false</includePluginDependencies>
					<classpathScope>compile</classpathScope>
				</configuration>
			</plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>1.3.3</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <createDependencyReducedPom>false</createDependencyReducedPom>
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                  <mainClass>org.apache.storm.flux.Flux</mainClass>
                  <manifestEntries>
                    <Change></Change>
                    <Build-Date></Build-Date>
                  </manifestEntries>
                </transformer>
              </transformers>
              
              <filters>
                <filter>
                  <artifact>*:*</artifact>
                  <excludes>
                    <exclude>META-INF/*.SF</exclude>
                    <exclude>META-INF/*.DSA</exclude>
                    <exclude>META-INF/*.RSA</exclude>
                  </excludes>
                </filter>
              </filters>
            </configuration>
          </execution>
        </executions>
      </plugin>

		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>org.apache.storm</groupId>
			<artifactId>storm-core</artifactId>
			<version>1.0.2</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.storm</groupId>
			<artifactId>flux-core</artifactId>
			<version>1.0.2</version>
		</dependency>
    <dependency>
      <groupId>com.github.crawler-commons</groupId>
      <artifactId>crawler-commons</artifactId>
      <version>${crawler-commons.version}</version>
    </dependency>
		<dependency>
			<groupId>com.digitalpebble.stormcrawler</groupId>
			<artifactId>storm-crawler-core</artifactId>
			<version>${storm.crawler.version}</version>
		</dependency>
    <dependency>
      <groupId>com.digitalpebble.stormcrawler</groupId>
      <artifactId>storm-crawler-elasticsearch</artifactId>
      <version>${storm.crawler.version}</version>
    </dependency>
   
    <dependency>
      <groupId>us.codecraft</groupId>
      <artifactId>xsoup</artifactId>
      <version>${xsoup.version}</version>
    </dependency>
    <dependency>
      <groupId>com.machinepublishers</groupId>
      <artifactId>jbrowserdriver</artifactId>
      <version>0.17.8-SNAPSHOT</version>
    </dependency>
  </dependencies>

**Error Log:** 
java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.common.network.NetworkService
	at org.elasticsearch.client.transport.TransportClient.newPluginService(TransportClient.java:98) ~[stormjar.jar:?]
	at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:126) ~[stormjar.jar:?]
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:268) ~[stormjar.jar:?]
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:125) ~[stormjar.jar:?]
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:111) ~[stormjar.jar:?]
	at com.digitalpebble.stormcrawler.elasticsearch.ElasticSearchConnection.getClient(ElasticSearchConnection.java:86) ~[stormjar.jar:?]
	at com.digitalpebble.stormcrawler.elasticsearch.ElasticSearchConnection.getConnection(ElasticSearchConnection.java:148) ~[stormjar.jar:?]
	at com.digitalpebble.stormcrawler.elasticsearch.persistence.StatusUpdaterBolt.prepare(StatusUpdaterBolt.java:141) ~[stormjar.jar:?]
	at org.apache.storm.daemon.executor$fn__6571$fn__6584.invoke(executor.clj:798) ~[storm-core-1.0.1.2.5.0.0-1245.jar:1.0.1.2.5.0.0-1245]
	at org.apache.storm.util$async_loop$fn__554.invoke(util.clj:482) [storm-core-1.0.1.2.5.0.0-1245.jar:1.0.1.2.5.0.0-1245]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
2017-04-24 08:23:42.554 o.a.s.d.executor [ERROR] 
java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.common.network.NetworkService
	at org.elasticsearch.client.transport.TransportClient.newPluginService(TransportClient.java:98) ~[stormjar.jar:?]
	at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:126) ~[stormjar.jar:?]
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:268) ~[stormjar.jar:?]
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:125) ~[stormjar.jar:?]
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:111) ~[stormjar.jar:?]
	at com.digitalpebble.stormcrawler.elasticsearch.ElasticSearchConnection.getClient(ElasticSearchConnection.java:86) ~[stormjar.jar:?]
	at com.digitalpebble.stormcrawler.elasticsearch.ElasticSearchConnection.getConnection(ElasticSearchConnection.java:148) ~[stormjar.jar:?]
	at com.digitalpebble.stormcrawler.elasticsearch.persistence.StatusUpdaterBolt.prepare(StatusUpdaterBolt.java:141) ~[stormjar.jar:?]
	at org.apache.storm.daemon.executor$fn__6571$fn__6584.invoke(executor.clj:798) ~[storm-core-1.0.1.2.5.0.0-1245.jar:1.0.1.2.5.0.0-1245]
	at org.apache.storm.util$async_loop$fn__554.invoke(util.clj:482) [storm-core-1.0.1.2.5.0.0-1245.jar:1.0.1.2.5.0.0-1245]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
2017-04-24 08:23:42.543 o.a.s.util [ERROR] Async loop died!
java.lang.ExceptionInInitializerError: null
	at org.elasticsearch.common.logging.DeprecationLogger.<clinit>(DeprecationLogger.java:138) ~[stormjar.jar:?]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.<init>(AbstractXContentParser.java:57) ~[stormjar.jar:?]
	at org.elasticsearch.common.xcontent.json.JsonXContentParser.<init>(JsonXContentParser.java:44) ~[stormjar.jar:?]
	at org.elasticsearch.common.xcontent.json.JsonXContent.createParser(JsonXContent.java:103) ~[stormjar.jar:?]
	at org.elasticsearch.common.settings.Setting.parseableStringToList(Setting.java:832) ~[stormjar.jar:?]
	at org.elasticsearch.common.settings.Setting.lambda$listSetting$27(Setting.java:786) ~[stormjar.jar:?]
	at org.elasticsearch.common.settings.Setting.listSetting(Setting.java:791) ~[stormjar.jar:?]
	at org.elasticsearch.common.settings.Setting.listSetting(Setting.java:786) ~[stormjar.jar:?]
	at org.elasticsearch.common.network.NetworkService.<clinit>(NetworkService.java:50) ~[stormjar.jar:?]
	at org.elasticsearch.client.transport.TransportClient.newPluginService(TransportClient.java:98) ~[stormjar.jar:?]
	at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:126) ~[stormjar.jar:?]
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:268) ~[stormjar.jar:?]
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:125) ~[stormjar.jar:?]
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:111) ~[stormjar.jar:?]
	at com.digitalpebble.stormcrawler.elasticsearch.ElasticSearchConnection.getClient(ElasticSearchConnection.java:86) ~[stormjar.jar:?]
	at com.digitalpebble.stormcrawler.elasticsearch.ElasticSearchConnection.getConnection(ElasticSearchConnection.java:148) ~[stormjar.jar:?]
	at com.digitalpebble.stormcrawler.elasticsearch.ElasticSearchConnection.getConnection(ElasticSearchConnection.java:130) ~[stormjar.jar:?]
	at com.digitalpebble.stormcrawler.elasticsearch.metrics.MetricsConsumer.prepare(MetricsConsumer.java:93) ~[stormjar.jar:?]
	at org.apache.storm.metric.MetricsConsumerBolt.prepare(MetricsConsumerBolt.java:75) ~[storm-core-1.0.1.2.5.0.0-1245.jar:1.0.1.2.5.0.0-1245]
	at org.apache.storm.daemon.executor$fn__6571$fn__6584.invoke(executor.clj:798) ~[storm-core-1.0.1.2.5.0.0-1245.jar:1.0.1.2.5.0.0-1245]
	at org.apache.storm.util$async_loop$fn__554.invoke(util.clj:482) [storm-core-1.0.1.2.5.0.0-1245.jar:1.0.1.2.5.0.0-1245]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
	at org.elasticsearch.Build.<clinit>(Build.java:49) ~[stormjar.jar:?]
	... 23 more

**Comment by jnioche** [comment]
https://github.com/elastic/elasticsearch/blob/5.3/core/src/main/java/org/elasticsearch/Build.java#L49
wondering what the [stormjar.jar:?] could correspond to? something added by hdp? could you try on a standalone Storm distribution?

**Comment by jnioche** [comment]
@saikatmohajan any luck?

**Comment by saikatmohajan** [comment]
Hey Julien, 
                  I haven't tried running on stand alone server yet. Will try soon and keep you posted. and also trying to figure out why it's picking up an storm jar without the version information in it. 
Thank you.

**Comment by jnioche** [comment]
Closing for now.

**Comment by ericxu131** [comment]
@saikatmohajan Try to upgrade lucene version. I fixed this error when i changed lucene version from 6.5.1 to 6.6.1.
